'use strict'

module.exports = [
  [/\sI\s/g, " Me "],
  [/I\s/g, "Me "],
  [/hillary\sclinton/gi, 'President Hillary'],
  [/hillary/gi, 'PresHRC'],
  [/long/gi, 'short'],
  [/fake/gi, 'real'],
  [/achievements/gi, 'tiny hands'],
  [/great/gi, 'terrible'],
  [/strong/gi, 'weak'],
  [/big/gi, 'tiny'],
  [/sad/gi, 'rad'],
  [/putin/gi, 'Putin<3'],
  [/Melania/gi, 'Wife#3'],
  [/\sNRA\s/g, ' TSA '],
  [/democrats/gi, 'adults'],
  [/without/gi, 'w/o'],
  [/with/gi, 'w/'],
  [/\sfor\s/gi, ' 4 '],
  [/\sto\s/gi, ' 2 '],
  [/really/gi, 'rly'],
  [/before/gi, 'b4'],
  [/u\.s\./gi, 'US'],
  [/u\.s\.a\./gi, 'USA'],
  [/\sand\s/gi, ' & '],
  [/china/gi, 'Jina'],
  [/fantastic/gi, 'mediocre'],
  [/\sthe\s/gi, ' da '],
  [/!/g, '?'],
  [/make\samerica\sgreat\sagain/gi, 'MAKE AMERICA SMART AGAIN'],
  [/huge/gi, 'yuge'],
  [/healthcare/gi, 'Trumpcare'],
  [/obamacare/gi, 'Obama cares'],
  [/president/gi, 'Prez'],
  [/god/gi, 'dong'] // #shoutout
]